backend:
  name: github
  # change repo to your git repository url
  repo: FarrenRE/my-blog

media_folder: static/assets
public_folder: /assets

collections:
  - name: settings
    label: Settings
    files:
      - name: config
        label: Config
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Site Title
            required: true
          - widget: string
            name: siteUrl
            label: Website URL
            required: true
          - widget: text
            name: description
            label: Description
            default: ''
            required: false
          - widget: object
            name: home
            label: Homepage Options
            fields:
              - widget: string
                name: title
                label: Title
                default: ''
                required: false
              - widget: markdown
                name: description
                label: Description
                default: ''
                required: false
  - name: blog
    label: Blog
    folder: _data/blog
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost
        }
      - { 
          name: date, 
          label: Date, 
          widget: datetime,
          required: false
        }
      - {
          name: path,
          label: Path,
          widget: string,
          pattern: [/],
          hint: "Path must start with /",
        }
      - {
          name: externalPath,
          label: External Path,
          widget: string,
          required: false
        }
      - {
          name: order,
          label: Order,
          widget: string,
          hint: "Uses flex order, -1 will display first",
          required: false
        }
      - { 
          name: title, 
          label: Title,
          required: false
        }
      - {
          name: tagline,
          label: Tagline,
          wisget: string,
          required: false
        }
      - {
          label: Meta Description,
          name: metaDescription,
          widget: text,
          required: false
        }
      - {
          label: Featured Image,
          name: thumbnail,
          widget: image,
          hint: "Image size 1280x800 works best :)",
          required: false,
          media_library: {
            config: {
              multiple: false
            }
          }
        }
      - label: "Links"
        name: "links"
        widget: "object"
        summary: '{{fields.name}}'
        collapsed: true
        required: false
        fields:
          - label: "External"
            name: "external"
            widget: "string"
            hint: "https://..."
            required: false
          - label: "Github"
            name: "github"
            widget: "string"
            hint: "https://www.github.com/..."
            required: false
          - label: "Linkedin"
            name: "linkedin"
            widget: "string"
            hint: "https://www.linkedin.com/..."
            required: false
          - label: "Stack Overflow"
            name: "stackoverflow"
            widget: "string"
            hint: "https://www.stackoverflow.com/..."
            required: false
          - label: "Ravelry"
            name: "ravelry"
            widget: "string"
            hint: "https://www.ravelry.com/..."
            required: false
      - {
          name: github,
          label: Github,
          widget: string,
          hint: "https://www.github.com/...",
          required: false
        }
      - {
          name: linkedin,
          label: Linkedin,
          widget: string,
          hint: "https://www.linkedin.com/...",
          required: false
        }
      - {
          name: stackoverflow,
          label: Stackoverflow,
          widget: string,
          hint: "https://www.stackoverflow.com/...",
          required: false
        }
      - {
          name: ravelry,
          label: Ravelry,
          widget: string,
          hint: "https://www.ravelry.com/...",
          required: false
        }
      - { 
          name: body, 
          label: Body, 
          widget: markdown,
          required: false
        }
      - {
          name: draft,
          label: Publish as draft?,
          widget: boolean,
          required: false,
          default: false
        }
